---
- name: Install Certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    mode: 0755
    dest: /usr/bin/certbot-auto
- name: Run Certbot
  command: certbot-auto -n --nginx --no-bootstrap --domains sonar-ssl.fastfeedback.rocks --agree-tos --register-unsafely-without-email
